version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node-app:latest
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm start"

